# Generated by Django 3.1.6 on 2021-03-28 15:21

from django.db import migrations, models
import django.db.models.deletion
import taggit.managers
import themes.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('taggit', '0003_taggeditem_add_unique_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(help_text='Category description upto 160 charchaters for SEO.', max_length=160, verbose_name='SEO description')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
                ('tags', taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Technology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Technology',
                'verbose_name_plural': 'Technologies',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('subtitle', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(blank=True)),
                ('seo_description', models.TextField(blank=True, help_text='Description to display in the meta tag.', max_length=160, verbose_name='SEO description')),
                ('theme_version', models.CharField(blank=True, default='', max_length=10)),
                ('bootstrap_version', models.IntegerField(choices=[(3, '3.x'), (4, '4.x'), (5, '5.x')], default=4)),
                ('is_published', models.BooleanField(default=True, verbose_name='published')),
                ('is_featured', models.BooleanField(default=False, verbose_name='featured')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('file', models.FileField(blank=True, help_text='Archived theme file.', null=True, upload_to=themes.models.themes_upload_location, verbose_name='theme file')),
                ('preview_url', models.URLField(blank=True, help_text='URL to deployed verion of the website.', max_length=255)),
                ('source_url', models.URLField(blank=True, help_text='URL to original theme website.', max_length=255)),
                ('repo_url', models.URLField(blank=True, help_text='URL to the repository.', max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('is_free', models.BooleanField(default=False, help_text='Not a premium theme.', verbose_name='free')),
                ('download_count', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='themes', to='themes.category')),
                ('tags', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags')),
                ('technologies', models.ManyToManyField(blank=True, to='themes.Technology')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='ThemeFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.CharField(max_length=255)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='themes.theme')),
            ],
            options={
                'order_with_respect_to': 'theme',
            },
        ),
    ]
