# Generated by Django 3.1.6 on 2021-04-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='photo',
            field=models.ImageField(blank=True, help_text='Recommended size 900x600 px.', null=True, upload_to=''),
        ),
    ]
