# Generated by Django 3.0.7 on 2020-09-12 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0002_theme_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='preview_url',
            field=models.URLField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
