# Generated by Django 3.0.7 on 2020-09-16 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0005_auto_20200913_2340'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='updated_at',
        ),
        migrations.RemoveField(
            model_name='themephoto',
            name='updated_at',
        ),
    ]
