# Generated by Django 3.0.7 on 2020-09-16 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0006_auto_20200917_0031'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='subtitle',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
