# Generated by Django 3.1.6 on 2021-03-08 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0007_auto_20210308_2317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='preview_url',
            field=models.URLField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='theme',
            name='repo_url',
            field=models.URLField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='theme',
            name='source_url',
            field=models.URLField(blank=True, default='', max_length=255),
            preserve_default=False,
        ),
    ]
