# Generated by Django 3.1.6 on 2021-03-08 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0008_auto_20210308_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='preview_url',
            field=models.URLField(blank=True, help_text='URL to deployed verion of the website.', max_length=255),
        ),
        migrations.AlterField(
            model_name='theme',
            name='repo_url',
            field=models.URLField(blank=True, help_text='URL to the repository.', max_length=255),
        ),
        migrations.AlterField(
            model_name='theme',
            name='source_url',
            field=models.URLField(blank=True, help_text='URL to original theme website.', max_length=255),
        ),
    ]
