# Generated by Django 3.0.7 on 2020-09-21 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0008_theme_download_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='slug',
            field=models.SlugField(max_length=200, unique=True),
        ),
    ]
