# Generated by Django 3.0.7 on 2020-09-21 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0009_auto_20200921_2352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='theme',
            old_name='thumbnail',
            new_name='photo',
        ),
        migrations.DeleteModel(
            name='ThemePhoto',
        ),
    ]
