# Generated by Django 3.0.7 on 2020-09-21 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0010_auto_20200922_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theme',
            name='bootstrap_version',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='theme',
            name='theme_version',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
