# Generated by Django 3.1.6 on 2021-03-08 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0010_category_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(help_text='Category description upto 160 charchaters for SEO.'),
        ),
    ]
