# Generated by Django 3.1.6 on 2021-03-08 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0011_auto_20210308_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='seo_description',
            field=models.TextField(blank=True, help_text='Description to display in the meta tag.', max_length=160),
        ),
    ]
