# Generated by Django 3.1.6 on 2021-03-08 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0012_theme_seo_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(help_text='Category description upto 160 charchaters for SEO.', max_length=160, verbose_name='SEO description'),
        ),
        migrations.AlterField(
            model_name='theme',
            name='seo_description',
            field=models.TextField(blank=True, help_text='Description to display in the meta tag.', max_length=160, verbose_name='SEO description'),
        ),
    ]
