# Generated by Django 3.0.7 on 2020-09-22 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0016_auto_20200922_0310'),
    ]

    operations = [
        migrations.CreateModel(
            name='ThemeFeature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('theme', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='themes.Theme')),
            ],
            options={
                'order_with_respect_to': 'theme',
            },
        ),
    ]
