# Generated by Django 3.0.7 on 2020-09-22 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0017_themefeature'),
    ]

    operations = [
        migrations.RenameField(
            model_name='themefeature',
            old_name='title',
            new_name='summary',
        ),
    ]
