# Generated by Django 3.1.6 on 2021-02-26 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shared', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='first_name',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='subscription',
            name='is_subscribed',
            field=models.BooleanField(default=True, verbose_name='subscribed'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='last_name',
            field=models.CharField(blank=True, max_length=60),
        ),
    ]
