# Generated by Django 3.1.6 on 2021-03-27 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('themes', '0001_initial'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='themes',
            field=models.ManyToManyField(blank=True, related_name='purchases', to='themes.Theme'),
        ),
    ]
