# Generated by Django 3.0.7 on 2020-10-11 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cart_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='uuid',
        ),
    ]
