# Generated by Django 3.0.7 on 2020-11-03 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0003_auto_20200923_0025'),
        ('cart', '0003_remove_cart_uuid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=120)),
                ('last_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('themes', models.ManyToManyField(blank=True, related_name='purchases', to='themes.Theme')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
