# Generated by Django 3.0.7 on 2020-11-11 20:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_purchase'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Purchase',
        ),
    ]
